model:
  encoder: resnet34
  skip_ch: 64
  aux_losses: 2
  dropout: 0.3
  weights: ResNet34_Weights.IMAGENET1K_V1
  noise_seed: 42
  n_tr: 0.0
  alpha: 2.0
  fig: A

data:
  type: voc2012_aug
  num_classes: 21
  num_workers: 0
  batch_size: 16
  max_training_samples: -1

train:
  seed: 42
  epochs: 52
  lr: 0.0002
  weight_decay: 0.0005
  optimizer: adamw
  accum_steps: 4
  resume: ''
  save_name: u3p_resnet34_voc_focal_epochs_52_no_warm_up_imagenet1k_v2_add_noise_0
  loss_type: focal
  warmup_iters: 3000

  logger:
    use_tensorboard: True
    log_dir: ./runs



