model:
  encoder: resnet34
  skip_ch: 64
  aux_losses: 2
  pretrained: True
  n_tr: 0.12
  fig: C

data:
  type: voc2012_aug
  num_classes: 21
  num_workers: 0
  batch_size: 16
  max_training_samples: -1

train:
  seed: 54
  epochs: 52
  lr: 0.0002
  weight_decay: 0.0005
  optimizer: adamw
  accum_steps: 4
  resume: ''
  save_name: u3p_resnet34_voc_focal_epochs_52_imagenet1k_v2_add_noise_7_e-2_seed_54
  loss_type: focal
  warmup_iters: 3000

  logger:
    use_tensorboard: True
    log_dir: ./runs

test:
  seed: 54
  weight: ./runs/u3p_resnet34_voc_focal_epochs_52_imagenet1k_v2_add_noise_12_e-2_seed_54/u3p_resnet34_voc_focal_epochs_52_imagenet1k_v2_add_noise_12_e-2_seed_54_last.ckpt
  save_name: u3p_resnet34_voc_focal_epochs_52_imagenet1k_v2_add_noise_12_e-2_seed_54
  loss_type: focal

  logger:
    use_tensorboard: True
    log_dir: ./test_runs
